import Image from "next/image";
import styles from "./page.module.scss";
import AlbumCover from "@/components/photography/AlbumCover";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Home - SP",
    description: "Generated by create next app",
  };

const Home = () => {
  return (
    <>
    </>
  );
}

export default Home;

